composer.lock
=> upgrade packages

.github/workflows/build-and-deploy.yml, helm/templates/deployment.yaml
=> auto recreate pod on successful deployment

app/Console/Commands/CreateUser.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Helpers/FormTemplateHelper.php, app/Models/FormDataSource.php, app/Models/FormVersion.php, database/migrations/2024_10_03_231629_create_data_sources_table.php, database/migrations/2024_10_03_232256_create_form_version_form_data_sources_table.php, database/seeders/DatabaseSeeder.php, database/seeders/FormDataSourceSeeder.php
Created ICM data sources for form metadata. Also added role selection when creating a user.
ICM data sources are needed when creating ICM forms.
This change was reviewed and agreed upon with other developers.
=> Form data sources

app/Filament/Bre/Resources/DataValidationResource.php, app/Filament/Bre/Resources/FieldResource.php, app/Filament/Bre/Resources/ICMCDWFieldResource.php, app/Filament/Bre/Resources/RuleResource.php, app/Models/BREField.php, app/Models/BRERule.php, database/migrations/2024_10_23_185853_add_unique_constraint_bre_rules_name.php
Updates to:
- `FieldResource`, `DataValidationResource`, `ICMCDWFieldResource`, and `RuleResource` classes 
- The addition of new filters, infolist schemas, and modifications to existing table columns and routes.
- Updating of routes to the unique name fields for bre fields and rule fields.
- Ensuring the `name` field for bre rules is unique and required.
To improve user interface navigability and usability.
N/A
=> BRE minor fixes and UI changes

app/Filament/Forms/Resources/SelectOptionsResource.php
Label need to be displayed instead of internal id when selecting a form field
=> Changes for ADO-2170

app/Filament/Forms/Resources/FieldGroupResource/Pages/EditFieldGroup.php, app/Filament/Forms/Resources/FormFieldResource.php, app/Filament/Forms/Resources/FormFieldResource/Pages/EditFormField.php, app/Filament/Forms/Resources/SelectOptionsResource.php, app/Filament/Home/Pages/Welcome.php, app/Helpers/FormTemplateHelper.php, app/Models/FieldGroup.php, app/Models/FormField.php, resources/views/filament/home/pages/welcome.blade.php
- select options for radio buttons output in the json
- select options being shown in the edit form field tab
- when trying to delete a form field, it won't let you if that form field exists in a form version
Hot fix bugs in form cataloguing
N/A
=> Status message page

app/Filament/Forms/Resources/FormFieldResource.php
Makes the label a required attribute
Hotfix to make the label required
N/A
=> make label required

app/Filament/Forms/Resources/FormFieldResource.php, app/Filament/Forms/Resources/FormFieldResource/Pages/CreateFormField.php, app/Filament/Forms/Resources/FormFieldResource/Pages/EditFormField.php, app/Filament/Forms/Resources/FormFieldResource/Pages/ViewFormField.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php, app/Helpers/FormTemplateHelper.php, app/Models/FormField.php, app/Models/FormFieldValue.php, app/Models/FormInstanceField.php, app/Models/FormInstanceFieldValue.php, database/migrations/2024_11_19_184713_create_form_instance_field_values_table.php, database/migrations/2024_11_21_194917_create_form_field_values_table.php
Fixed PR for Saranya
https://github.com/bcgov/klamm/pull/39
Just cloned the branch and cherry picked the commit we needed.
N/A
=> Changes for ADO-2036

app/Filament/Forms/Resources/FormDataSourceResource.php, app/Filament/Forms/Resources/FormDataSourceResource/Pages/CreateFormDataSource.php, app/Filament/Forms/Resources/FormDataSourceResource/Pages/EditFormDataSource.php, app/Filament/Forms/Resources/FormDataSourceResource/Pages/ListFormDataSources.php, app/Filament/Forms/Resources/FormDataSourceResource/Pages/ViewFormDataSource.php
Created form data source resource.
To edit form data sources from KLAMM.
None.
=> Created form datasource resource

app/Filament/Forms/Resources/FormDataSourceResource.php
Added Databinding sources label for navigation
Resource is not showing KLAMM under Form Metadata. Added the label to be consistent with other Resources under Form Metadata.
None.
=> Added Databinding sources label for navigation

app/Filament/Forms/Resources/FormVersionResource.php
Made fields cloneable inside and outside of groups. Unfortunately could not find a way to update the Custom ID, meaning these will have to be updated manually. 
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2203
Considered ways to provide a callback to the cloneable() method in order to update the Custom ID, but wasn't able to find a solution
=> Duplicate fields ADO 2203

app/Filament/Forms/Resources/SelectOptionsResource.php, app/Models/FormField.php, app/Models/SelectOptions.php, database/migrations/2024_12_31_000819_form_field_select_options.php, database/migrations/2025_01_03_234421_remove_form_field_id_from_select_options_table.php
Created many-to-many relationship (with pivot table) between Select Options and Form Field
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2173
None
=> Many-to-many relationship between Select Options and Form Field

app/Filament/Forms/Resources/FormVersionResource.php
Removed section headers "Form Field Settings" and "Field Group Settings"
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2279/
None
=> Remove section headers ADO 2279

README.md, database/seeders/UserSeeder.php
updated repo location in readme and added user to UserSeeder.php
repo name out of date and learning KLAMM
n/a
=> updated repo location in readme

helm/values.yaml
=> add values for queue worker

helm/templates/deployment.yaml, helm/values.yaml
This will run the queue worker in another small pod
So we can export to csv as a background task. Also this will be needed for any of the bulk import tasks Joh has lined up.
I thought about running it a bunch of different ways but this was the simplest and takes advantage of OpenShift's infrastructure. Instead of using some script with the Dockerfile this will make use of pod retries and hopefully be a bit easier to see what is going on.
=> Deploy queue runner

app/Helpers/FormTemplateHelper.php
Fixed bug where JSON couldn't render due to not handling FormField/SelectOptions many-to-many relationship
Bugfix
None
=> JSON template handles FormField/SelectOption many-to-many relationship

app/Http/Controllers/SystemMessageController.php
=> fix searching for error codes

app/Filament/Fodig/Resources/ErrorActorResource.php, app/Filament/Fodig/Resources/ErrorActorResource/Pages/CreateErrorActor.php, app/Filament/Fodig/Resources/ErrorActorResource/Pages/EditErrorActor.php, app/Filament/Fodig/Resources/ErrorActorResource/Pages/ListErrorActors.php, app/Filament/Fodig/Resources/ErrorActorResource/Pages/ViewErrorActor.php, app/Filament/Fodig/Resources/ErrorDataGroupResource.php, app/Filament/Fodig/Resources/ErrorDataGroupResource/Pages/CreateErrorDataGroup.php, app/Filament/Fodig/Resources/ErrorDataGroupResource/Pages/EditErrorDataGroup.php, app/Filament/Fodig/Resources/ErrorDataGroupResource/Pages/ListErrorDataGroups.php, app/Filament/Fodig/Resources/ErrorDataGroupResource/Pages/ViewErrorDataGroup.php, app/Filament/Fodig/Resources/ErrorEntityResource.php, app/Filament/Fodig/Resources/ErrorEntityResource/Pages/CreateErrorEntity.php, app/Filament/Fodig/Resources/ErrorEntityResource/Pages/EditErrorEntity.php, app/Filament/Fodig/Resources/ErrorEntityResource/Pages/ListErrorEntities.php, app/Filament/Fodig/Resources/ErrorEntityResource/Pages/ViewErrorEntity.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource/Pages/CreateErrorIntegrationState.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource/Pages/EditErrorIntegrationState.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource/Pages/ListErrorIntegrationStates.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource/Pages/ViewErrorIntegrationState.php, app/Filament/Fodig/Resources/ErrorSourceResource.php, app/Filament/Fodig/Resources/ErrorSourceResource/Pages/CreateErrorSource.php, app/Filament/Fodig/Resources/ErrorSourceResource/Pages/EditErrorSource.php, app/Filament/Fodig/Resources/ErrorSourceResource/Pages/ListErrorSources.php, app/Filament/Fodig/Resources/ErrorSourceResource/Pages/ViewErrorSource.php, app/Filament/Fodig/Resources/SystemMessageResource.php
=> add error tables for system messages

app/Filament/Forms/Resources/FieldGroupResource.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php, app/Helpers/FormTemplateHelper.php, app/Models/FieldGroup.php, app/Models/FieldGroupInstance.php, database/migrations/2025_01_20_185620_add_data_bindings_to_groups.php
Added functionality for data bindings & data source on Groups - create, edit, view, and apply to JSON template
Implement https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2322
None - implemented the same way that customizable properties were done for fields
=> Add (customizable) data bindings to Groups

app/Filament/Forms/Resources/FormVersionResource.php, app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
Minor refactor to solve issue of missing values for Custom Label radios in fields within groups
Resolve https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2300/
None
=> Fix bug 2300

app/Filament/Bre/Resources/RuleResource.php
Minor update to amend graphical error introduced in previous update.
bugfix
=> Quick fix to BRE badge formatting.

app/Filament/Components/ContainerBlock.php, app/Filament/Components/FieldGroupBlock.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php, app/Helpers/FormTemplateHelper.php, app/Models/Container.php, app/Models/FormInstanceField.php, app/Models/FormVersion.php, app/Models/StyleInstance.php, database/migrations/2025_02_11_214814_add_containers.php
Added ability to create Containers in the FormVersion builder. Also refactored several large files to facilitate this and future changes
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2128
None
=> Containers ADO 2128

app/Helpers/FormTemplateHelper.php
Added SelectOptions values to JSON for dropdowns and radios
Implement https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2371/
None
=> Include select options values in JSON ADO 2371

app/Filament/Reports/Resources/ReportEntryResource.php
=> move data matching rate in reports

app/Console/Commands/ImportReportsFromCsv.php, app/Filament/Reports/Resources/ReportBusinessAreaResource.php, app/Filament/Reports/Resources/ReportDictionaryLabelResource.php, app/Filament/Reports/Resources/ReportEntryResource.php, app/Filament/Reports/Resources/ReportLabelSourceResource.php, app/Filament/Reports/Resources/ReportResource.php, app/Providers/AppServiceProvider.php, app/Providers/Filament/ReportsPanelProvider.php, database/seeders/PermissionsSeeder.php, database/seeders/RolesSeeder.php
=> report view only setup

app/Filament/Reports/Resources/ReportEntryResource.php, app/Filament/Reports/Resources/ReportEntryResource/Pages/ListReportEntries.php, database/seeders/ReportLabelSourceSeeder.php
=> change label names, move exporter

app/Filament/Fodig/Resources/ErrorActorResource.php, app/Filament/Fodig/Resources/ErrorDataGroupResource.php, app/Filament/Fodig/Resources/ErrorEntityResource.php, app/Filament/Fodig/Resources/ErrorIntegrationStateResource.php, app/Filament/Fodig/Resources/ErrorSourceResource.php, app/Filament/Fodig/Resources/PopularPageSystemMessageResource.php, app/Filament/Fodig/Resources/PopularPageSystemMessageResource/Pages/CreatePopularPageSystemMessage.php, app/Filament/Fodig/Resources/PopularPageSystemMessageResource/Pages/EditPopularPageSystemMessage.php, app/Filament/Fodig/Resources/PopularPageSystemMessageResource/Pages/ListPopularPageSystemMessages.php, app/Filament/Fodig/Resources/PopularPageSystemMessageResource/Pages/ViewPopularPageSystemMessage.php, app/Filament/Fodig/Resources/SystemMessageResource.php, app/Models/PopularPageSystemMessage.php, app/Policies/FormVersionPolicy.php, app/Policies/PopularPageSystemMessagePolicy.php, database/migrations/2025_03_24_160852_create_popular_page_system_messages_table.php, database/seeders/PermissionsSeeder.php
Adds a popular pages section to the system messages.
This is a blank section of the exporter I forgot to add earlier
N/A
=> System Messages - Popular pages

helm/templates/queue-deployment.yaml, helm/values.yaml
=> add mail envs to queue runner

helm/values.yaml
=> Fix 1 core to 1

helm/templates/deployment.yaml, helm/templates/pvc.yaml, helm/templates/queue-deployment.yaml, helm/values.yaml
Moved the shared pvc to allow many write/read access
we were getting multi attach problems when scaling up
N/A
=> Merge dev into production

app/Filament/Reports/Resources/ReportEntryResource/Pages/ListReportEntries.php
=> add description to report entries

app/Console/Commands/ImportReportsFromCsv.php, app/Filament/Reports/Resources/ReportEntryResource.php
=> add source data field

app/Filament/Exports/ReportEntryExporter.php, app/Filament/Reports/Resources/ReportEntryResource.php, app/Filament/Reports/Resources/ReportEntryResource/Pages/ViewReportEntry.php, resources/views/filament/reports/report-entry/subheading.blade.php
=> update label match rating label

app/Filament/Reports/Resources/ReportEntryResource.php
changes download bulk action colour
=> update download colour

app/Models/ReportEntry.php
=> set default values for data_matching and follow_up

app/Filament/Fodig/Resources/BoundarySystemContactResource.php, app/Filament/Fodig/Resources/BoundarySystemContactResource/Pages/ListBoundarySystemContacts.php, app/Filament/Fodig/Resources/BoundarySystemInterfaceResource.php, app/Filament/Fodig/Resources/BoundarySystemInterfaceResource/Pages/ListBoundarySystemInterfaces.php, app/Filament/Fodig/Resources/BoundarySystemInterfaceResource/Pages/ViewBoundarySystemInterface.php, app/Filament/Fodig/Resources/BoundarySystemResource/Pages/ListBoundarySystems.php, app/Filament/Fodig/Resources/BoundarySystemTagResource/Pages/ListBoundarySystemTags.php, app/Providers/Filament/AdminPanelProvider.php, app/Providers/Filament/BrePanelProvider.php, app/Providers/Filament/FodigPanelProvider.php, app/Providers/Filament/FormsPanelProvider.php, app/Providers/Filament/HomePanelProvider.php, resources/views/filament/home/pages/welcome.blade.php
Changes the edit page so most elements are full width. Also shortened the description limit.
UI changes requested by service designer
N/A
=> wip: update UI of boundary systems

app/Helpers/FormTemplateHelper.php
Eager load styles on groups
Bug fix for https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2537/
None
=> Eager load styles for groups

Dockerfile
Bringing this change:
https://github.com/bcgov/klamm/pull/162
=> increase default php memory limit

database/migrations/2025_04_28_234121_lengthen_labels_and_javascript.php
Changed type of some columns from varchar to text
Need to accommodate more than 255 chars in certain cases (including demoing CF0322)
Considered increasing size of varchar, but text is more flexible and is used elsewhere in the database
=> Change label and javascript columns from varchar(255) to text

app/Filament/Forms/Pages/FormsDashboard.php, app/Filament/Forms/Widgets/FormsDescriptionWidget.php, app/Filament/Forms/Widgets/FormsStatsWidget.php, app/Filament/Forms/Widgets/YourFormsWidget.php, app/Filament/Home/Pages/Profile.php, app/Providers/Filament/FormsPanelProvider.php, resources/views/filament/forms/widgets/forms-description.blade.php
for the dashboard:
Brings a description to the top.
Brings a "your forms" table if you have any forms
Brings the stats widget if you are an admin
Clean up the dashboard which was not useful currently
N/A
=> Update forms dashboard

app/Filament/Forms/Widgets/YourFormsWidget.php
fixes pagination issue (was loading all by default)
=> fix default pagination and trim levels

resources/views/filament/forms/resources/form-resource/pages/view-form.blade.php
fixes the darkmode in the view form page
darkmode was bugged
=> fix darkmode in view page

app/Filament/Forms/Widgets/YourFormsWidget.php, resources/views/filament/forms/resources/form-resource/pages/view-form.blade.php
Ticket getting released:
- #177
=> Merge Dev into Main

app/Console/Commands/ImportReportsFromCsv.php, public/reports.csv, resources/views/filament/reports/resources/report-entry-resource/pages/list-report-entries.blade.php
Adds final set of data for the data load
=> Update reports with final data load

app/Filament/Components/ContainerBlock.php, app/Filament/Components/FieldGroupBlock.php, app/Filament/Components/FormFieldBlock.php, app/Filament/Components/FormVersionBuilder.php, app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php, app/Helpers/FormDataHelper.php
Improve KLAMM performance by caching database calls, using lazy instead of live/reactive where possible, dehydrating, and collapsing sections
Work on demo form CF0322 (https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2541) ground to a halt after ~120 elements due to poor performance. 
None
=> Performance optimizations

app/Filament/Components/FormVersionBuilder.php, app/Helpers/FormTemplateHelper.php, app/Models/FormVersion.php, database/migrations/2025_05_08_232101_add_form_footer.php
Added footer property to formVersion and JSON template
ADO https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2558
None
=> Add form footer property ADO 2558

.github/workflows/build-and-deploy.yml
Set the permissions we need for each step in the github workflow as per code scan suggestions.
https://github.com/bcgov/klamm/security/code-scanning/6
https://github.com/bcgov/klamm/security/code-scanning/7
https://github.com/bcgov/klamm/security/code-scanning/8
N/A
=> Set GitHub actions permissions

database/factories/BusinessAreaFactory.php, database/factories/UserFactory.php, tests/Feature/Auth/AuthenticationTest.php, tests/Feature/Auth/AuthorizationTest.php, tests/Feature/Auth/RoleAuthorizationTest.php, tests/Feature/ExampleTest.php, tests/Pest.php, tests/README.md, tests/TestCase.php, tests/Unit/UserModelTest.php, tests/Unit/UserRelationshipsTest.php, tests/Unit/UserValidationTest.php
Added tests on user models and RBAC setup
We need higher test coverage and I started with users since it was a pretty foundational part of the app
N/A
=> Add test coverage

.github/workflows/build-and-deploy.yml, database/seeders/RolesSeeder.php, phpunit.xml
Fixes the GitHub actions test setup to use sqlite
=> setup sqlite for test workflow

.github/workflows/build-and-deploy.yml
Force uses sqlite in the github actions workflow
=> set sqlite database for testing in workflow

.github/workflows/build-and-deploy.yml
Fix an error with malformed env file when overriding
=> stop overriding .env file

.github/workflows/build-and-deploy.yml, phpunit.xml
Disable foreign keys for sqlite compatibility.
=> disable foreign keys in testing.

.github/workflows/build-and-deploy.yml, phpunit.xml
Rather than using sqlite in the test workflow, we will just use Postgres
=> use postgres in github actions

app/Models/User.php
When emails are set, they get saved as lowercase in the db
=> save emails in the db to lowercase

app/Filament/Forms/Resources/FormResource.php
Shows the ICM generated metadata in the view page
Information deemed as necessary
N/A
=> Show ICM Generated in View Page

app/Filament/Fodig/Resources/BoundarySystemContactResource.php, app/Filament/Fodig/Resources/BoundarySystemInterfaceResource/Pages/ViewBoundarySystemInterface.php, app/Filament/Fodig/Resources/BoundarySystemResource.php, app/Models/BoundarySystemContact.php, app/Models/BoundarySystemInterface.php, database/migrations/2025_05_27_043048_update_boundary_system_interface_enums.php, database/seeders/BoundarySystemBaseSeeder.php, database/seeders/BoundarySystemContactSeeder.php, database/seeders/BoundarySystemInterfaceSeeder.php, database/seeders/BoundarySystemSeeder.php, database/seeders/BoundarySystemTagSeeder.php, database/seeders/DatabaseSeeder.php
Seeds all the boundary systems
So we can have the initial boundary system data in Klamm
Seeding straight from a csv but this was easier
=> Boundary system seed real data

app/Filament/Components/FormVersionBuilder.php, app/Filament/Forms/Resources/ApprovalRequestResource.php, app/Filament/Forms/Resources/ApprovalRequestResource/Pages/EditApprovalRequest.php, app/Filament/Forms/Resources/ApprovalRequestResource/Pages/ListApprovalRequests.php, app/Filament/Forms/Resources/ApprovalRequestResource/Pages/ViewApprovalRequest.php, app/Filament/Forms/Resources/FormResource/Pages/ViewForm.php, app/Filament/Forms/Resources/FormVersionResource/Actions/FormApprovalActions.php, app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php, app/Filament/Home/Pages/ExternalApprovalReview.php, app/Forms/Components/ShowMorePlaceholder.php, app/Helpers/ImportTemplateHelper.php, app/Models/FormVersion.php, app/Notifications/ApprovalDecisionNotification.php, app/Notifications/ApprovalRequestNotification.php, app/Providers/Filament/HomePanelProvider.php, app/Traits/HandlesApprovalReview.php, database/migrations/2025_05_29_042523_update_form_versions_remove_updater_and_add_developer_id.php, database/seeders/FormInstanceSeeder.php, resources/views/filament/home/pages/external-approval-review.blade.php, resources/views/forms/components/show-more-placeholder.blade.php
⚠️ View PDF and View Webform buttons don't work yet ⚠️
**See comment below**
Part of the release management implementation. This piece will allow people to approve or reject forms.
N/A
=> Approval Page / Release Management

helm/templates/deployment.yaml, helm/templates/form-data-pvc.yaml, helm/values.yaml
Makes the helm changes necessary to setup and bind a pvc to hold the css files. Tested and working on the Test env.
=> openshift for form data pvc

tests/Feature/Auth/RoleAuthorizationTest.php
=> Model Refactor: disable tests for now

tests/Feature/Auth/AuthenticationTest.php, tests/Feature/Auth/AuthorizationTest.php, tests/Unit/ExampleTest.php, tests/Unit/UserModelTest.php, tests/Unit/UserRelationshipsTest.php, tests/Unit/UserValidationTest.php
=> Model Refactor: Remove remaining tests

app/Filament/Forms/Resources/FormResource/RelationManagers/FormVersionRelationManager.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Helpers/FormVersionHelper.php, app/Models/FormBuilding/ButtonInputFormElement.php, app/Models/FormBuilding/CheckboxInputFormElement.php, app/Models/FormBuilding/ContainerFormElement.php, app/Models/FormBuilding/DateSelectInputFormElement.php, app/Models/FormBuilding/HTMLFormElement.php, app/Models/FormBuilding/NumberInputFormElement.php, app/Models/FormBuilding/RadioInputFormElement.php, app/Models/FormBuilding/SelectInputFormElement.php, app/Models/FormBuilding/TextInfoFormElement.php, app/Models/FormBuilding/TextInputFormElement.php, app/Models/FormBuilding/TextareaInputFormElement.php
Add action to duplicate form version
Re-adding feature from old Klamm
None
=> Duplicate form version action

Dockerfile
=> Add npm build to workflow.

.github/workflows/build-and-deploy.yml
Queue worker will auto restart now
If we made changes that the queue worker required, we would have to manually restart it
Just leave it and do it manually.
=> also restart the queue-worker

app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php, app/Filament/Home/Pages/Profile.php, app/Livewire/FormElementTreeBuilder.php, app/Models/FormBuilding/FormElement.php, app/Models/User.php, app/Providers/Filament/HomePanelProvider.php, app/Services/FormVersionJsonService.php, database/migrations/2025_07_09_151821_add_tooltips_enabled_to_users_table.php, database/migrations/2025_07_09_160129_remove_is_visible_from_form_elements_table.php
=> Fix/form builder UI ux updates

config/livewire.php
=> fix string 'null' to null null

app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php, app/Livewire/FormElementTreeBuilder.php, app/Services/FormVersionJsonService.php
Shows the toggles for Read Only and Save on Submit
Passes that data to the JSON template too
Request from forms team
N/A
=> show read only and save on submit

Dockerfile, helm/templates/deployment.yaml, helm/templates/queue-deployment.yaml
=> Shared volume permissions

app/Filament/Forms/Resources/FormResource/RelationManagers/FormVersionRelationManager.php, app/Filament/Forms/Resources/FormVersionResource.php, app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php, app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php, app/Helpers/DataBindingsHelper.php, app/Helpers/SchemaHelper.php, app/Jobs/ImportFormVersionElementsJob.php, app/Models/FormBuilding/DateSelectInputFormElement.php, app/Models/FormBuilding/FormElement.php, app/Models/FormBuilding/FormElementDataBinding.php, app/Models/FormBuilding/SelectInputFormElement.php, app/Services/FormVersionJsonService.php, database/migrations/2025_07_17_200804_add_default_selected_to_select_input_form_elements_table.php, database/migrations/2025_07_17_202507_add_condition_to_form_element_data_bindings_table.php
- Adds defaultSelected to dropdowns
- Updates the list of date options
- Data Bindings have a condition field
- Fixes the required field by fixing the Version 1.0 template conditionals and validations to look exactly like Kiln needs it.
- Makes the preview buttons consistent
- Autogenerate the labelText based on the Element Name
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8140
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8125
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8142
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8148
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8153
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8134
https://github.com/user-attachments/assets/7b5b92ea-9f99-41d6-9f74-bebe2 …
=> Small bug fixes

app/Filament/Components/FormVersionBuilder.php, app/Filament/Forms/Resources/FormScriptResource.php, app/Filament/Forms/Resources/StyleSheetResource.php, database/migrations/2025_07_17_092909_increase_styles_scripts_description_length.php, scripts/ScriptTemplates/CalculatedScripts.js, scripts/ScriptTemplates/ConditionalScripts.js
- Update display of descriptions for form scripts and stylesheets when using select picker for insertion. 
- update the db to support longer descriptions.
- add scripts to 'Scripts' folder for re-use in-app
=> Update script/styles descriptions and add script/style templates.

app/Helpers/GeneralTabHelper.php, app/Helpers/SchemaHelper.php, app/Models/FormBuilding/DateSelectInputFormElement.php, app/Models/FormBuilding/FormElement.php, app/Services/FormVersionJsonService.php, database/migrations/2025_07_25_210344_increase_label_text_column_length.php, database/migrations/2025_07_25_213025_update_empty_date_format_values.php
- labelText is now 1000 chars long up from 255
- date format is now a required field and pre-filled to YYYY-MMM-DD
- Hide the label if hideLabel is marked as true
- Template type is in the dropdown name
https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3103
https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3097
https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3093
=> Multiple bug fixes

app/Services/FormVersionJsonService.php
Inside of using the labelText attribute we are using the label property part of the form element.
Hiding and showing and setting labels wasn't working.
=> Fix labels

app/Helpers/GeneralTabHelper.php
- Custom Visibility tooltip now is conditional
=> Additional bug fixes

app/Services/FormVersionJsonService.php
Return databindings as lowercase and updated source name to 'source'. 
Updated per requested format per [3086](https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3086). 
N/A
=> Update databindings export format to match requested.

app/Services/FormVersionJsonService.php
Removes the labelText which was overriding the label in Kiln.
Required fields should now show the asterisk.
N/A
=> remove labelText from v1 schema

public/js/sveltescript.js
- minor change to svelte injection script to fix event handling in svelte kiln
=> Minor updates to svelte injection script to fix checkbox issues.

app/Filament/Components/FormVersionBuilder.php, app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php, app/Helpers/FormVersionHelper.php
added helper to get visible fields and try skipping soft deleted/ghost fields
Try to prevent error pop up showed up for ghost fields
=> Ado 3354 Form Standard Check failing on element that doesn't exist(BUG)
