app/Filament/Exports/FormExporter.php
app/Filament/Forms/Resources/FormResource.php
app/Models/Form.php
app/Providers/Filament/FormsPanelProvider.php
database/migrations/2024_10_11_011958_add_form_program_to_forms_table.php
database/migrations/2024_10_11_024036_create_notifications_table.php
database/migrations/2024_10_11_024309_create_imports_table.php
database/migrations/2024_10_11_024310_create_exports_table.php
database/migrations/2024_10_11_024311_create_failed_import_rows_table.php

Bug: duplicate form_id returns 500 not a warning when trying to edit/create
In the Form List Viewer:
- “Ministry” column show the short name ("MCFD") to save space.
- “Decommissioned” column can be removed, since there is a universal on/off filter for this value
Add new field/property to a form:
- “Program” – text field -- it is useful for when a large business area like SDD wants to list a specific Program.
Weird behaviour the "Related Forms" field. It’s a small list and I don't recognize them. It doesn't seem to be the ID or title.
Feature request: (let me know if this is reasonable)
- export the form list as CSV, with all fields
Update form viewer/editor layout order to:
- Form ID
- Form Title
- Ministry
- Business Area
- Program
- Form Purpose
- Notes
- Decommissioned
- ICM Generated …

Ado 2007 bug fix

---

app/Filament/Forms/Resources/FormResource.php
app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
app/Helpers/FormTemplateHelper.php
app/Models/FieldGroupInstance.php
app/Models/FormInstanceField.php
app/Models/FormInstanceFieldValidation.php
app/Models/FormVersion.php
database/migrations/2024_10_03_180857_remove_field_group_constraint.php
database/migrations/2024_10_03_180917_create_field_group_instance_table.php
database/migrations/2024_10_03_180933_add_field_group_instance_constraint.php
database/migrations/2024_10_29_074036_add_order_to_field_group_instances_table.php
database/seeders/DatabaseSeeder.php

Adds form groups to the form versioning system
We need to accommodate forms having both form fields and field groups that contain form fields.
I am actually storing all the relationships as fields and form groups and doing some order assigning and whatnot in the database fields. I considered using some string manipulation such as adding the prefix grp- or fld- but that did not feel sustainable long term and it was error prone. This was quite a challenging feature implementation due to Filament not supporting a lot of these features so it takes a bit of effort to make it work.

Form groups for form versions

---

app/Filament/Admin/Resources/UserResource.php
app/Filament/Admin/Resources/UserResource/Pages/ViewUser.php
app/Filament/Forms/Resources/FieldGroupResource.php
app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php

- You can swap order of form fields within a field group
- The components are displayed in readonly in the View mode of Form Version
- You can manage what form fields are inside a field group by editing a field group
- You can reset a users password from the view user screen in the admin panel
These were all brought up as needed features with the Forms Team
Forms being within forms was another needed feature that I am not able to complete due to time constraints

Form group improvements

---

app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php

changed afterSave to afterCreate for the create class
afterSave was not running so no form fields would save when creating a new form version
none

use afteCreate in the create class

---

.github/dependabot.yml

Moved dependabot to make it's PRs in the dev env
Since our CI/CD path goes from Dev->Main these PRs from dependabot directly into main were a bit of a problem since they wouldn't get passed into dev in any way.
N/A

Update dependabot to open PRs in dev

---

app/Filament/Fodig/Resources/SystemMessageResource.php
app/Filament/Forms/Resources/FormVersionResource.php

Added a button so you can move published form versions to the archived status
Request from Rob in the forms team
I could have enabled the drop down in the edit page but having this as an action in the list made more sense.

Allow moving published form versions to archived

---

app/Filament/Forms/Resources/FormVersionResource.php

Added more descriptive labels to fields that display the name and type of field or group
Makes fields/groups easier to identify and removes extraneous information (see https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2202)
No alternative way to implement this feature

More descriptive labels when adding and viewing a field/group

---

app/Filament/Forms/Resources/FieldGroupResource.php

For FieldGroups, made Label required and Repeater not required.
Label is required to create and properly display a FieldGroup. Repeater is technically required, but as it is a boolean, it always already has a value. When creating/editing a FieldGroup, making it required is confusing because it implies it is supposed to be set to True - removing the requirement solves this
None

Update field group requirements

---

app/Helpers/FormTemplateHelper.php

Added the 'deployed to' field from the form version to the metadata of the generated JSON.
Will be used to specify which version is deployed to in the Template Repository. This field will dictate which version of the form will  be used to generate the ICM version. 
None

Added 'deployed_to' to json definition

---

app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php
app/Helpers/FormTemplateHelper.php
app/Models/FieldGroupInstance.php
app/Models/FormInstanceField.php
app/Models/FormInstanceFieldValue.php
database/migrations/2024_12_23_224628_add_custom_properties_to_form_fields.php

Added UI and functionality for custom properties on Fields in the Version Builder. Where custom properties exist, they overwrite the default properties in the JSON form template. 
Implementing ADO 2229 https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2229
None

Intuitive display override customize version builder ado 2229

---

app/Filament/Forms/Resources/FieldGroupResource.php
app/Filament/Forms/Resources/FormFieldResource.php
app/Filament/Forms/Resources/SelectOptionsResource.php

Enforced uniqueness of names for Fields, Groups, and Select Options (at the front-end level). Also made name, label, and (in the case of Select Options) values searchable in the view table, which will help identify any existing duplicated names
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2223
Considered adding validation to the database, but frontend is sufficient and avoids any potential errors with any existing duplicates, which can be safely caught fixed manually

Enforce unique names ADO 2223

---

app/Filament/Forms/Resources/FormFieldResource.php
app/Filament/Forms/Resources/FormVersionResource.php

Added item labels referencing the Validation Type options value
Implemented https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2230/
None

Validation headers ADO 2230

---

app/Filament/Forms/Resources/FormFieldResource.php
app/Filament/Forms/Resources/FormVersionResource.php

Added searchable, sortable, filterable data_bindings column to FormFields table
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2234/
None

Form fields table add data binding column ADO 2234

---

app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php

Fields now display in the format 'Label | type | id: instanceID'
Groups display 'Label | group | id: instanceID'
Field selectors display 'Label | type | name: fieldName'
Group selectors display ''Label | type | name: groupName'
Also fixed a bug where the Label part of the element header does not update when a different field is selected.
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2318/
Discussed alternative formats and the utility of including the Name property in the Element header (we decided having it in the Selector was enough)

Improved FormVersion element headers

---

app/Helpers/FormTemplateHelper.php

Set "helperText" to help text property of FieldInstance/Field for all field types, and removed "placeholder" on text-input and redundant "helpText" key
Resolving https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2312/
None

Fix placeholder and helperText in JSON

---

app/Filament/Forms/Resources/FormVersionResource.php

Resolved bug by wrapping the field data inside the 'data' array key, as expected by the builder
Resolving https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2361/
None

Attached fields not being added to groups ADO 2361

---

app/Filament/Components/FormFieldBlock.php
app/Filament/Forms/Resources/FormFieldResource.php

Used RichEditor component for Value property of fields with type text-info, instead of TextInput or Textarea
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2384/
Considered using Textarea and Markdown components, but RichEditor is the richest and most compatible with KILN's side of the implementation

Use RichEditor for text-info Value property

---

app/Filament/Forms/Resources/SelectOptionsResource.php

Make value required for SelectOptions (on the front-end only)
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2372/
None

Make value property required on SelectOptions ADO 2372

---

app/Filament/Components/FormFieldBlock.php
app/Filament/Forms/Resources/FormFieldResource.php
app/Filament/Forms/Resources/FormFieldResource/Pages/CreateFormField.php
app/Filament/Forms/Resources/FormFieldResource/Pages/EditFormField.php
app/Filament/Forms/Resources/FormFieldResource/Pages/ViewFormField.php
app/Filament/Forms/Resources/FormFieldsRelationManagerResource/RelationManagers/FormFieldsRelationManager.php
app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php
app/Filament/Forms/Resources/SelectOptionsResource.php
app/Filament/Forms/Resources/SelectOptionsResource/RelationManagers/FormInstanceFieldsRelationManager.php
app/Helpers/FormTemplateHelper.php
app/Models/FormField.php
app/Models/FormInstanceField.php
app/Models/SelectOptionInstance.php
app/Models/SelectOptions.php
database/migrations/2025_02_21_193254_add_order_to_form_field_select_options_table.php

Allows for sorting and ordering SelectOptions for dropdown and radio -type Fields and FieldInstances, as well as viewing which Fields/FormInstances a SelectOption is used on. While this update uses SelectOptionInstances on Fields (1-many relationship) instead of SelectOptions (many-many), it should preserve the associations (although Fields will still have to be updated once to set the desired order)
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_sprints/backlog/FormFoundry/Forms%20Modernization/02-12-2025%20(Sprint%2032)?workitem=2304&System.AreaPath=FormFoundry&System.AssignedTo=%40me
Considered modifying the multi-select for the many-to-many relationship between Fields and SelectOptions, as well as using RelationManagers to set the order for SelectOptions on fields, …

Sort and order select options ADO 2304

---

app/Filament/Components/ContainerBlock.php
app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php
app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/FormVersionResource/Pages/CreateFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
app/Helpers/FormTemplateHelper.php

Updated form elements to use sequential instance IDs, regardless of nesting level. Uses Session to store counter
Implementing https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2419
Considered various ways of storing counter

Sequential element IDs ADO 2419

---

app/Filament/Forms/Resources/FormVersionResource/Pages/EditFormVersion.php
app/Filament/Forms/Resources/FormVersionResource/Pages/ViewFormVersion.php
app/Helpers/FormTemplateHelper.php

Adds eager loading to the formField properties needed in this component
In the previous changes I added the functionality in the AppServiceProvider to locally throw an error when lazy loading occurs. In going through the application I found that lazy loading was happening in the view and FormVersion edit and view pages. I eager loaded the remaining needed resources.
Then in the generateJsonTemplate function the same was happening so I fixed that as well.
One thing that might still be an issue is in the nested relationships with groups and containers. The preventLazyLoading isn't throwing any errors here but I could see it still being an issue. Will investigate this further.
N/A

fix eager loading on form fields

---

helm/templates/queue-deployment.yaml

Moves the queue runner to a separate pod rather than a container within the klamm app
If we want to scale up the Laravel app we don't want to scale up a bunch of queue runners. This way we can independently scale up the queue runner or the application as needed. We pretty rarely use the queue runner for imports and exports so it is fine if it doesn't get scaled up when the application does.
Just leaving it as is. But this is the best for the long term health of Klamm.

move queue runner to pod rather than in container

---

app/Http/Controllers/BREFieldController.php
app/Http/Controllers/BREFieldGroupController.php
app/Http/Controllers/BRERuleController.php
app/Http/Controllers/ICMCDWFieldController.php

- Update to the bre api controllers to enable eager loading rather than lazy loading. Loading of nested properties is now explicit. 
- Added additional functionality to allow for querying of rules/fields using the rule/field name in addition to the id.
- Exact information returned in query is now explicit, and easy to understand, add/remove properties.
- Eager loading minimizes number of database queries
- Looked into re-enabling lazy loading for local development for api queries only, but overall, explicit querying and improvements to database queries preferred.

Update bre controllers to eager load properties for fields/rules.

---

Dockerfile

Increased the default PHP memory_limit
We were encountering this error:
```
$ cat laravel.log
[2025-04-23 17:08:39] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12783504 bytes) {"userId":7,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 12783504 bytes) at /var/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:63)
[stacktrace]
#0 {main}
"} 
```
The container has a 1gb memory request but was restricted by PHP to only use 128mb
Manually editing php.ini or setting up the change with laravels env variables or in the helm chart. This was the cleanest and recommended from Laravel.

increase default php memory limit

---

app/Helpers/FormTemplateHelper.php

Get selectOptionInstances from the fieldInstance, not the field, so that any selectOptionInstances added in the builder are captured
Bugfix https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2540
None

Bugfix: JSON missing radio select options 

---

app/Helpers/FormTemplateHelper.php

Get selectOptionInstances from the fieldInstance, not the field, so that any selectOptionInstances added in the builder are captured
Bugfix https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2540
None

Cherry pick Radio Bugfix from DEV

---

app/Filament/Components/ContainerBlock.php
app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php

Element header only update when custom label/ID blurs. Group headers use custom label values
Resolving two bugs:
- https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2542
- https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2385
Considered the differences between debounce(), lazy(), live(), and reactive()

Bugfix element label

---

app/Filament/Components/ContainerBlock.php
app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php

Use resizable Textarea instead of TextInput for JavaScript input fields
Single line text input is annoying and not ideal for writing code
None

Use Textareas for JavaScript input

---

app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php

Truncate overly long labels and append ' ...' to prevent element from overstretching
Resolve https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2549/
None

Limit length of labels in element headers to 50 characters

---

app/Filament/Components/FormVersionBuilder.php
app/Filament/Forms/Resources/FormFieldsRelationManagerResource/RelationManagers/FormFieldsRelationManager.php
app/Filament/Forms/Resources/FormVersionResource.php
app/Filament/Forms/Resources/SelectOptionsResource.php
app/Filament/Forms/Resources/SelectOptionsResource/RelationManagers/FormInstanceFieldsRelationManager.php
app/Models/FormVersion.php
composer.json
composer.lock
database/migrations/2025_05_06_050214_create_activity_log_table.php
database/migrations/2025_05_06_050215_add_event_column_to_activity_log_table.php
database/migrations/2025_05_06_050216_add_batch_uuid_column_to_activity_log_table.php
database/migrations/2025_05_06_054952_update_form_versions_enum.php

- Adds the https://github.com/spatie/laravel-activitylog package
- Logs status changes for form versions
- Changes the statuses to use the new system outlined here https://knowledge.social.gov.bc.ca/klamm/forms_release_management
Part of the new release management system involves tracking all the changes. Adding this package and tracking status changes is a good start. Right now it is set to "logOnlyDirty" so it only logs the attributes which have been updated, it is also set to log the 'status', 'form_id' and 'version_number'.
To run and test this you will need to run `sail composer install` to grab the new package. Then make sure to run the migrations.
The activity log right now is tracking whether it was created vs updated (important distinction), who did the change, and when. From the …

Add activity log setup and update version statuses

---

composer.json
composer.lock
storage/debugbar/.gitignore

Adds the laravel debug bar
https://laraveldebugbar.com/installation/#install-with-composer
You will need to run `sail composer install` to get the debug bar
This is really useful for debugging as you can see the queries the page is running and other insights. It only runs when APP_DEBUG is set to true and is in the dev dependencies so it won't run on our live environments.
Other debug tools, but this is one I am familiar with.

add laravel debug bar

---

database/seeders/FormFieldSeeder.php

Added seeders for generic fields
Generic fields are required to exist for the JSON importer to function correctly
None

Add seeders for generic fields

---

app/Filament/Forms/Resources/FormVersionResource.php

Change the column name reference for the status in the form versions.
Since searchable searches the actual column name, use that rather than the computed name I was using.
Custom search query.

fix status search for form versions

---

app/Filament/Components/ContainerBlock.php
app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php
app/Filament/Components/FormVersionBuilder.php
app/Helpers/FormDataHelper.php

- Switch to block previews option for blocks components in builder on form version.
- Modify the form load query to load incrementally depending on form version view.
- Add additional functionality to generate json button to also copy to clipboard.
- Intended to speed up form version creation by reducing queries on initial page load. Full implementation pending potential caching update to take more advantage of reduced db queries.

Form Version block previews 

---

app/Filament/Components/FieldGroupBlock.php
app/Filament/Components/FormFieldBlock.php

Just changes the icons in the form builder to match the left metadata
Just so our icons are all aligned across Klamm
N/A

Update the Form Builder "Add element" Icon

---

database/migrations/2024_07_16_145421_add_tables_for_forms_workflow.php

Fix an issue with sqlite migrations where primary and id can't both be called on a field.

fix the id/primary duplication for sqlite

---

helm/templates/deployment.yaml
helm/templates/queue-deployment.yaml
helm/values.yaml

Limits the revision history to 3 (replica set count)
There was large amounts of replica sets accumulating. It was set to 10 max but it was getting to way more than 10
You can manually delete them with commands like:
```
oc get replicasets --no-headers | grep 'klamm-app.*0.*0.*0' | awk '{print $1}' | xargs oc delete replicaset
```
```
oc get replicasets --no-headers | grep 'klamm-queue-worker.*0.*0.*0' | awk '{print $1}' | xargs oc delete replicaset
```

limit revision history

---

helm/Chart.yaml
helm/templates/queue-deployment.yaml
helm/templates/reverb-deployment.yaml
helm/templates/reverb-service.yaml
helm/values.yaml

Add deployment for consistent implementation of reverb websockets and live preview functionality.
Required to enable automatic updates of deployment, and keep reverb worker up to date with changes to klamm image.
Individual deployment, but would not be flexible and up-to-date with current implementation of queue worker.

Add reverb worker to helm deployment

---

app/Filament/Admin/Resources/UserResource.php
app/Filament/Admin/Resources/UserResource/Pages/CreateUser.php
app/Filament/Forms/Resources/BusinessAreaResource.php
app/Models/User.php
app/Notifications/AccountCreatedNotification.php
app/Providers/AppServiceProvider.php
app/Providers/Filament/BrePanelProvider.php
app/Providers/Filament/FodigPanelProvider.php
app/Providers/Filament/FormsPanelProvider.php
database/factories/UserFactory.php
database/migrations/2025_06_06_231156_consolidate_view_only_roles_to_user_role.php
database/seeders/PermissionsSeeder.php
database/seeders/RolesSeeder.php
tests/Feature/Auth/RoleAuthorizationTest.php
tests/README.md
tests/TestCase.php

Consolidates
- forms-view-only
- bre-view-only
- fodig-view-only
into the 'user' role.
There are updates to the gates and panels to handle this. The migration does 2 things:
- goes through all users who have the view only role and gives them the user role
- goes through all users without a role, and gives them the user role
You will need to run:
```
sail artisan migrate
sail artisan db:seed --class=PermissionsSeeder
```
To simplify our RBAC system instead of having 3 different view only users we are defining one "user" role which will be a catch all user that has view only access to all resources.
Removing the view only role all together, but we want to keep the flexibility in the future for our "users" in the event we need to expand the RBAC setup.

Consolidate view only roles to "user"

---

app/Notifications/ApprovalDecisionNotification.php
app/Notifications/ApprovalDecisionReviewerNotification.php
app/Notifications/ApprovalRequestNotification.php
app/Notifications/ApprovalRequestReminderNotification.php
app/Notifications/CancellationNotification.php

Minor bugfix to remove duplicate salutations using default app name.

Fix salutation duplication in email notifications.

---

app/Filament/Components/FormVersionBuilder.php

Automatically assign the current user as the Form Developer when creating a new form. 
ADO https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/2722
None

Assign the current user by default as the FormVersion developer

---

app/Notifications/ApprovalRequestNotification.php

Removed the line for the Klamm@gov.bc.ca email
We currently do not have access to an email to use for this. When we do we can update the email templates.
I was thinking we could use an alternative but there isn't a generic Forms Team email and I think adding Rob's email (even if pulled from a CONTACT_EMAIL env) wouldn't be a good solution for now.

Remove klamm email

---

app/Filament/Forms/Resources/FormVersionResource.php
database/migrations/2025_07_10_235814_modify_form_elements_uuid_constraint.php

Makes UUIDs unique per form version
Makes UUIDs duplicate when you duplicate a form version
The duplication is important since we use those UUIDs in the styles and data bindings. So we need to keep them consistent between different versions of the same form.
N/A

make UUID unique to each form version

---

app/Models/FormBuilding/ContainerFormElement.php
app/Services/FormVersionJsonService.php
database/migrations/2025_07_15_063520_add_repeater_item_label_to_container_form_elements_table.php

Adds custom repeater labels.
Since you might have a legend for the container but each element inside it needs a short name like "Child 1", "Child 2", etc
N/A

allow custom repeater labels

---

app/Providers/Filament/AdminPanelProvider.php
app/Providers/Filament/FormsPanelProvider.php
app/Providers/Filament/HomePanelProvider.php

Recent updates to the Rsramos activity log plugin necessitate additional settings to function properly. Have added those properties to the universal imports on the admin panel, form panel, and home panel.
Without these, the view action was not available for any activity logs across the site.

Fix to requirements in plugin following update.

---

app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php
app/Livewire/FormElementTreeBuilder.php
app/Models/FormBuilding/ContainerFormElement.php

- Makes tree nested items not collapsed by default
- Auto generates the Legend/Title of a container

More Bug Fixes

---

app/Services/FormVersionJsonService.php

Containers transformed into repeating groups were not including the UUID. This was due to how kiln was setup to handle groups. However, kiln was not currently using a unique id on the parent group element, so by adding the ...item.attributes spread in the groups in kiln in this commit: https://github.com/kiiskila-bcgov/klamm-kiln/commit/abe37c1bcaf0517e6d62f55c36ce2aec84bfd280, we can now pass the UUID directly to kiln and provide repeating groups with custom uuids. This makes styling/calculations substantially easier to manage.

Add attributes for repeater group id.

---

app/Helpers/GeneralTabHelper.php

Allows changing the reference ID after clicking a little lock
https://github.com/user-attachments/assets/794e2856-3c5e-4320-962b-584f9b8bbd38
The forms team mentioned they needed to change the reference IDs (especially when importing forms), but it shouldn't be super easy, there should be another action like a confirmation modal.
Confirmation modals don't work inside the tree editor page, so this was the best alternative I could come up with.

allow changing the reference ID

---

app/Helpers/SchemaHelper.php
app/Models/FormBuilding/CheckboxInputFormElement.php
app/Models/FormBuilding/DateSelectInputFormElement.php
app/Models/FormBuilding/NumberInputFormElement.php
app/Models/FormBuilding/RadioInputFormElement.php
app/Models/FormBuilding/SelectInputFormElement.php
app/Models/FormBuilding/TextInputFormElement.php
app/Models/FormBuilding/TextareaInputFormElement.php
database/migrations/2025_07_22_173755_remove_helper_text_from_form_elements.php

Some fields like text input had a helper text field but it is already a field that existed in the form element
https://dev.azure.com/bc-icm/FODIG/_workitems/edit/8163
Things like TextInfo probably shouldn't have a help text so it shouldn't be as part of the form element, but it doesn't hurt to leave it there for now.

remove duplicate helper text field

---

app/Helpers/GeneralTabHelper.php
app/Models/FormBuilding/FormElement.php
app/Services/FormVersionJsonService.php
database/migrations/2025_07_23_122203_add_custom_visibility_column_form_elements.php

- Re-enable support for custom scripts to dynamically control the visibility and read-only states of form elements. 
- Added `TextArea` inputs for defining custom visibility/readonly scripts in the form element.
- custom scripts for visibility and read-only conditions are passed on in the JSON v1 if provided. Defaults are used when custom scripts are not set.
Per [3034](https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3034/), required for conditional visibility and readonly status, while still allowing for saveonsubmit, in different server conditions.
Custom Javascript code. However, this is different from base form rendering/conditional visibility. These custom blocks pass information along to Kiln to specially render. This is similar to the [conditions created for the …

Re-add custom conditional visibility and readonly

---

app/Livewire/FormElementTreeBuilder.php
resources/views/filament/forms/resources/form-version-resource/pages/build-form-version.blade.php

- Uses the svg directly rather than redefining it in the livewire component for the add element
- Adds the preview to the sticky footer in the builder
- Adds the save button to the sticky footer in the builder
- Fixes a bug with the modal header name when deleting an element
- Control/Command + P for Preview
- Control/Command + N for New element (can't override cmd + n for new tab, but control works here for mac)
- Control/Command + S for Save
These were a number of QOL changes that Jeremy had requested.
N/A

Bug fixes and small feature add ons

---

app/Livewire/FormElementTreeBuilder.php
app/Models/FormBuilding/ContainerFormElement.php
database/migrations/2025_07_30_133636_add_label_level_container_form_element.php

- add optional "label level" (`level`) field for container form elements. 
- allowing users to choose a label level (e.g., `H2`, `H3`, etc.) or leave it as "No override" for default styling.
- Added a `nullableFields` array in both `mutateFormDataBeforeSave` and `mutateFormDataBeforeCreate` to allow values to be set back to null in the component attributes panel
Requested per [3095](https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3095/)
N/A

Add handling for header levels in containers/groups.

---

app/Filament/Components/FormVersionBuilder.php
app/Filament/Forms/Resources/FormInterfaceResource.php
app/Filament/Forms/Resources/FormInterfaceResource/Pages/ListFormInterfaces.php
app/Models/FormMetadata/FormInterface.php
app/Services/FormVersionJsonService.php
database/migrations/2025_08_20_121033_add_interface_column_mode.php

- add "mode" property to the `FormInterface` model.
- Enable null gating for stylesheet and script labeling in the form version builder to prevent errors when scripts/styles are not deleted with form versions.
- enhance attribute normalization to omit nullish or undefined values (causing issues with react carbon components when null values are set).
- followup to ticket [3127](https://dev.azure.com/BC-SDPR/Forms%20Modernization/_workitems/edit/3127)
- additional functionality in preparation for api interface integration

Fix - stylesheet cascade and add mode to interfaces

---

app/Filament/Forms/Resources/FormVersionResource/Pages/BuildFormVersion.php
database/seeders/UserTypeSeeder.php
resources/views/filament/forms/resources/form-version-resource/pages/build-form-version.blade.php

Allows user to copy the json structure as a "copy to clipboard"
I tried to refactor a little bit to make it easier to reuse the download and copy components
duplicating the code for each, but this was better although it took a little longer.

export json as copy-paste
